# ZTelegram Configuration
# Version 1.0

# Примечание: Используйте \n для переноса строки в сообщениях
# Пример: "Первая строка\nВторая строка"
#
# Поддерживаются градиенты и MiniMessage форматирование во всех сообщениях:
# <gradient:#FF0000:#A6EB0F>Текст в градиенте</gradient>
# <#FF0000>Текст HEX цветом
# &4Красный текст, §1Синий текст

# Bot settings
bot:
  token: "YOUR_TELEGRAM_BOT_TOKEN" # Get it from @BotFather
  username: "YOUR_BOT_USERNAME" # Bot username without @

# Main channel settings (for chat)
main_channel:
  enabled: true
  id: "YOUR_MAIN_CHANNEL_ID"
  chat_enabled: true
  format:
    telegram_to_minecraft: "<gray>[<gradient:#1E88E5:#64B5F6>Telegram</gradient>] <white>%player%</white><gray>:</gray> <white>%message%</white>"
    minecraft_to_telegram: "<b>%player%</b>: %message%"

# Register channel settings
register-channel:
  enabled: true
  id: "YOUR_REGISTER_CHANNEL_ID"
  invalid-username: "❌ Invalid username! Please enter a valid Minecraft username."
  already-registered: "❌ This username is already registered!"
  player-offline: "❌ Player %player% is not online. Please join the server first."
  success: "✅ Successfully registered! Your Minecraft username: %player%"
  success-in-game: "<gradient:#2ECC71:#4CAF50>%player% successfully linked Telegram account!</gradient>"
  reward-commands:
    - "eco give %player% 50"

# Console channel settings
console-channel:
  enabled: true
  id: "YOUR_CONSOLE_CHANNEL_ID"
  player-command-log:
    enabled: true
    format: "<gray>[Command] <white>%player%</white> executed: <gray>%command%</gray></gray>"
  command-feedback:
    enabled: true
    success: "✅ Command executed successfully!"
    error: "❌ Failed to execute command: %error%"

# Server events
events:
  server-start:
    enabled: true
    message: "🟩 <b>Server started!</b>"
  server-stop:
    enabled: true
    message: "🟥 <b>Server stopped!</b>"
  player-join:
    enabled: true
    message: "👋 <b>%player%</b> joined the server"
  player-quit:
    enabled: true
    message: "👋 <b>%player%</b> left the server"
  player-death:
    enabled: true
    message: "💀 <b>%player%</b> %reason%"
  player-chat:
    enabled: true
    message: "<b>%player%</b>: %message%"

# Telegram commands
commands:
  online:
    enabled: true
    response: |
      <gradient:#0052CC:#45B6FE>Online players: %online%/%max%</gradient>
      <gradient:#4CAF50:#8BC34A>Players: %players%</gradient>
  
  tps:
    enabled: true
    response: |
      <gradient:#0052CC:#45B6FE>Server TPS:</gradient>
      <gradient:#4CAF50:#8BC34A>%tps%</gradient>
  
  restart:
    enabled: true
    response: "<gradient:#FF0000:#FF9800>⚠️ Server restart initiated!</gradient>"

  gender:
    enabled: true
    usage: "Usage: /gender [man/girl] or /пол [м/ж]"
    no_player: "You need to register your nickname first!"
    response: "Gender for %player% set to %gender%"
    translations:
      man: "Male"
      girl: "Female"
  
  player:
    enabled: true
    usage: "Usage: /player <nickname>"
    no_player: "Player %player% not found"
    response: |
      Player: %player%
      Online: %online%
      Health: %health%
      Gender: %gender%
      Registered: %registered%
      First played: %first_played%
      Deaths: %deaths%
      Level: %level%
      Balance: %balance%
      Coordinates: %coords%
    translations:
      online: "Online"
      offline: "Offline"
      not_set: "Not set"
      not_registered: "Not registered"
      offline_coords: "Not available"
      never: "Never"
  
  # Command list command
  cmd_list:
    enabled: true
    response: |
      <gradient:#0052CC:#45B6FE>Доступные команды:</gradient>
      
      <gradient:#4CAF50:#8BC34A>• /online, /онлайн</gradient> - показать список игроков онлайн
      <gradient:#4CAF50:#8BC34A>• /tps, /тпс</gradient> - показать TPS сервера
      <gradient:#4CAF50:#8BC34A>• /restart, /рестарт</gradient> - перезапустить сервер
      <gradient:#4CAF50:#8BC34A>• /gender [man/girl], /пол [м/ж]</gradient> - установить свой пол
      <gradient:#4CAF50:#8BC34A>• /player [nickname], /ник [никнейм]</gradient> - информация об игроке
      <gradient:#4CAF50:#8BC34A>• /cmd, /команды</gradient> - показать список всех команд
      <gradient:#4CAF50:#8BC34A>• /game [nickname], /игра [никнейм]</gradient> - сыграть в игру "Угадай слово"

# Plugin settings
plugin:
  prefix: "§7[§b§lZTG§7]§r"
  telegram-link: "https://t.me/YOUR_TELEGRAM"
  telegram-command-message: "<gradient:#1E88E5:#64B5F6>Join our Telegram channel!</gradient>" 
